#!/usr/bin/env python3

import argparse
import csv
import math
import os
import sys

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
except Exception as exc:
    print(f"Failed to import matplotlib: {exc}", file=sys.stderr)
    sys.exit(1)


def _to_float(value: str) -> float:
    try:
        return float(value)
    except Exception:
        return float("nan")


def _load_csv_rows(csv_path: str) -> list[dict[str, str]]:
    with open(csv_path, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        return list(reader)


def _series(rows: list[dict[str, str]], key: str) -> list[float]:
    return [_to_float(row.get(key, "")) for row in rows]


def _plot_joint_grid(
    t: list[float],
    a: list[list[float]],
    b: list[list[float]],
    a_label: str,
    b_label: str,
    title: str,
    out_file: str,
) -> None:
    fig, axes = plt.subplots(3, 4, figsize=(18, 10), sharex=True)
    axes = axes.flatten()
    for i in range(12):
        ax = axes[i]
        ax.plot(t, a[i], label=a_label, linewidth=1.0)
        ax.plot(t, b[i], label=b_label, linewidth=1.0, alpha=0.85)
        ax.set_title(f"joint_{i}")
        ax.grid(True, alpha=0.3)
        if i >= 8:
            ax.set_xlabel("time [s]")
    axes[0].legend(loc="upper right", fontsize=8)
    fig.suptitle(title)
    fig.tight_layout()
    fig.savefig(out_file, dpi=140)
    plt.close(fig)


def _plot_norms(
    t: list[float],
    commanded: list[list[float]],
    actual: list[list[float]],
    out_file: str,
) -> None:
    commanded_norm = []
    actual_norm = []
    error_norm = []
    for idx in range(len(t)):
        cn = 0.0
        an = 0.0
        en = 0.0
        for j in range(12):
            cv = commanded[j][idx]
            av = actual[j][idx]
            cn += cv * cv
            an += av * av
            err = cv - av
            en += err * err
        commanded_norm.append(cn ** 0.5)
        actual_norm.append(an ** 0.5)
        error_norm.append(en ** 0.5)

    fig, ax = plt.subplots(figsize=(12, 4))
    ax.plot(t, commanded_norm, label="||commanded_joint_position||", linewidth=1.2)
    ax.plot(t, actual_norm, label="||actual_joint_position||", linewidth=1.2)
    ax.plot(t, error_norm, label="||commanded-actual||", linewidth=1.2)
    ax.set_title("Joint Position Norms")
    ax.set_xlabel("time [s]")
    ax.grid(True, alpha=0.3)
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_file, dpi=140)
    plt.close(fig)


def _plot_observation_subset(
    t: list[float],
    obs: list[list[float]],
    indices: list[int],
    labels: list[str],
    title: str,
    out_file: str,
) -> None:
    if not indices:
        return

    cols = 4
    rows = int(math.ceil(len(indices) / cols))
    fig, axes = plt.subplots(rows, cols, figsize=(18, 3.2 * rows), sharex=True)
    if rows == 1:
        axes = [axes] if not isinstance(axes, list) else axes
    axes = list(axes.flatten())  # type: ignore[union-attr]

    for plot_idx, obs_idx in enumerate(indices):
        ax = axes[plot_idx]
        ax.plot(t, obs[obs_idx], linewidth=1.0)
        ax.set_title(labels[plot_idx])
        ax.grid(True, alpha=0.3)
        if plot_idx >= (rows - 1) * cols:
            ax.set_xlabel("time [s]")

    for ax in axes[len(indices):]:
        ax.axis("off")

    fig.suptitle(title)
    fig.tight_layout()
    fig.savefig(out_file, dpi=140)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot policy debug CSV generated by record_policy_debug.py")
    parser.add_argument("csv", help="Path to debug CSV file")
    parser.add_argument(
        "--out-dir",
        default="",
        help="Output directory for plots (default: alongside CSV)",
    )
    args = parser.parse_args()

    csv_path = os.path.abspath(os.path.expanduser(args.csv))
    if not os.path.isfile(csv_path):
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    rows = _load_csv_rows(csv_path)
    if not rows:
        raise RuntimeError("CSV has no rows to plot.")

    out_dir = args.out_dir.strip()
    if not out_dir:
        base = os.path.splitext(os.path.basename(csv_path))[0]
        out_dir = os.path.join(os.path.dirname(csv_path), f"{base}_plots")
    out_dir = os.path.abspath(os.path.expanduser(out_dir))
    os.makedirs(out_dir, exist_ok=True)

    time_abs = _series(rows, "time_sec")
    t0 = time_abs[0]
    t = [x - t0 for x in time_abs]

    commanded = [_series(rows, f"commanded_joint_position_{i}") for i in range(12)]
    actual = [_series(rows, f"actual_joint_position_{i}") for i in range(12)]
    command_err = [_series(rows, f"commanded_minus_actual_joint_position_{i}") for i in range(12)]
    obs = [_series(rows, f"obs_{i}") for i in range(56)]

    _plot_joint_grid(
        t=t,
        a=commanded,
        b=actual,
        a_label="commanded_joint_position",
        b_label="actual_joint_position",
        title="Commanded vs Actual Joint Position",
        out_file=os.path.join(out_dir, "commanded_vs_actual_joint_position.png"),
    )
    _plot_joint_grid(
        t=t,
        a=command_err,
        b=[[0.0] * len(t) for _ in range(12)],
        a_label="commanded-actual",
        b_label="zero",
        title="Joint Position Tracking Error",
        out_file=os.path.join(out_dir, "joint_position_tracking_error.png"),
    )
    _plot_norms(
        t=t,
        commanded=commanded,
        actual=actual,
        out_file=os.path.join(out_dir, "joint_position_norms.png"),
    )

    # Observation layout:
    # 0..2 root_lin_vel, 3..5 root_ang_vel, 6..8 projected_gravity, 9..11 state_error,
    # 12..23 leg_joint_pos_rel, 24..35 leg_joint_vel, 36..37 pendulum_pos,
    # 38..39 pendulum_vel, 40..51 previous_action, 52..55 clock_inputs.
    obs_indices_non_leg_joints = list(range(0, 12)) + list(range(36, 40)) + list(range(52, 56))
    obs_labels_non_leg_joints = [
        "root_lin_vel_x (obs_0)",
        "root_lin_vel_y (obs_1)",
        "root_lin_vel_z (obs_2)",
        "root_ang_vel_x (obs_3)",
        "root_ang_vel_y (obs_4)",
        "root_ang_vel_z (obs_5)",
        "projected_gravity_x (obs_6)",
        "projected_gravity_y (obs_7)",
        "projected_gravity_z (obs_8)",
        "goal_error_x_body (obs_9)",
        "goal_error_y_body (obs_10)",
        "goal_error_yaw (obs_11)",
        "pendulum_joint_pos_0 (obs_36)",
        "pendulum_joint_pos_1 (obs_37)",
        "pendulum_joint_vel_0 (obs_38)",
        "pendulum_joint_vel_1 (obs_39)",
        "clock_input_0 (obs_52)",
        "clock_input_1 (obs_53)",
        "clock_input_2 (obs_54)",
        "clock_input_3 (obs_55)",
    ]
    _plot_observation_subset(
        t=t,
        obs=obs,
        indices=obs_indices_non_leg_joints,
        labels=obs_labels_non_leg_joints,
        title="Observation Channels (Non-Leg-Joint + Pendulum + Clock)",
        out_file=os.path.join(out_dir, "observations_non_leg_joint_with_pendulum.png"),
    )

    print(f"Saved plots to: {out_dir}")


if __name__ == "__main__":
    main()
